apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-frontend
  namespace: rabbit-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: rabbit-frontend
  template:
    metadata:
      labels:
        app: rabbit-frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: rabbit-frontend
              topologyKey: kubernetes.io/hostname
      containers:
        - name: frontend
          image: 926337676555.dkr.ecr.eu-west-3.amazonaws.com/rabbit-frontend:1.0
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: rabbit-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-frontend
  namespace: rabbit-app
spec:
  selector:
    app: rabbit-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP